import React, { useState, useEffect } from 'react';
import { CardData, DragItemType, OperationType } from '../types';
import Slot from './Slot';
import { X, Divide, Zap, RefreshCw, Calculator, ArrowRight, RotateCcw } from 'lucide-react';
import { formatNumber } from '../utils/mathUtils';

interface WorkbenchProps {
  slotA: CardData | null;
  slotB: CardData | null;
  onUpdateSlot: (slot: 'slotA' | 'slotB', card: CardData | null) => void;
  onCombine: (result: CardData, usedIds: string[]) => void;
  onReturnToHand: (card: CardData) => void; // If user removes from slot
  onDragStart: (e: React.DragEvent, card: CardData, source: 'hand' | 'slotA' | 'slotB') => void;
  onDropOnSlot: (e: React.DragEvent, slotId: 'slotA' | 'slotB') => void;
}

const Workbench: React.FC<WorkbenchProps> = ({ 
  slotA, 
  slotB, 
  onUpdateSlot, 
  onCombine, 
  onReturnToHand,
  onDragStart,
  onDropOnSlot
}) => {
  const [preview, setPreview] = useState<CardData | null>(null);
  const [selectedOp, setSelectedOp] = useState<OperationType>('MULTIPLY');

  // Reciprocal Logic for individual slots
  const applyReciprocal = (slotId: 'slotA' | 'slotB', card: CardData) => {
    const newVal = 1 / card.value;
    
    let newLabel = `1/(${card.label})`;

    // Check if we can toggle back (unwrap)
    // Case 1: Wrapped in 1/(...)
    if (card.label.startsWith('1/(') && card.label.endsWith(')')) {
        newLabel = card.label.slice(3, -1);
    }
    // Case 2: Simple fraction like "1/4" (generated by formatNumber)
    else if (/^1\/-?\d+(\.\d+)?$/.test(card.label)) {
        newLabel = card.label.substring(2);
    }

    const newCard: CardData = {
      id: Math.random().toString(36).substr(2, 9),
      value: newVal,
      label: newLabel,
      isOriginal: false
    };
    
    onUpdateSlot(slotId, newCard);
  };

  useEffect(() => {
    if (slotA && slotB) {
      calculateResult(selectedOp);
    } else {
      setPreview(null);
    }
  }, [slotA, slotB, selectedOp]);

  const calculateResult = (op: OperationType) => {
    if (!slotA || !slotB) return;

    let val = 0;
    let lbl = '';

    switch (op) {
      case 'MULTIPLY':
        val = slotA.value * slotB.value;
        lbl = `(${slotA.label} × ${slotB.label})`;
        break;
      case 'POWER_AB':
        val = Math.pow(slotA.value, slotB.value);
        lbl = `(${slotA.label} ^ ${slotB.label})`;
        break;
      default:
        return;
    }

    // Check for validity (finite, not NaN, not too massive)
    if (!isFinite(val) || isNaN(val)) {
        setPreview(null);
        return;
    }

    setPreview({
      id: 'preview', // Temporary ID
      value: val,
      label: formatNumber(val), // Show calculated value in preview for clarity
      isOriginal: false
    });
  };

  const handleExecute = () => {
    if (preview && slotA && slotB) {
        // Create the real card
        const finalCard = {
            ...preview,
            id: Math.random().toString(36).substr(2, 9),
            // We might want to keep the label complex:
            // label: selectedOp === 'MULTIPLY' ? `(${slotA.label} * ${slotB.label})` ...
            // But showing the number is often more useful for the user to track progress.
            // Let's stick to the formatted number for the label of the new card,
            // but maybe keep a tooltip for the expression?
            // Actually, the prompt says "make a target number". Usually seeing the number is key.
            label: formatNumber(preview.value) 
        };
        onCombine(finalCard, [slotA.id, slotB.id]);
        
        // Clear slots
        onUpdateSlot('slotA', null);
        onUpdateSlot('slotB', null);
        setPreview(null);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto mt-8 p-6 bg-slate-900/80 rounded-3xl border border-slate-700 shadow-2xl backdrop-blur-sm">
      <div className="flex flex-col md:flex-row items-center justify-center gap-8 md:gap-12 relative">
        
        {/* Background Connector Graphic */}
        <div className="absolute top-1/2 left-10 right-10 h-1 bg-slate-800 -z-10 hidden md:block rounded-full"></div>

        {/* Slot A */}
        <div className="relative group">
            <Slot 
            label="Input A" 
            slotId="slotA"
            card={slotA} 
            onDrop={onDropOnSlot}
            onRemove={() => slotA && onReturnToHand(slotA)}
            onDragStart={onDragStart}
            highlight={!slotA}
            />
             {/* Reciprocal Action */}
             {slotA && (
                <button 
                    onClick={() => applyReciprocal('slotA', slotA)}
                    className="absolute -bottom-10 left-1/2 -translate-x-1/2 text-xs flex items-center gap-1 text-emerald-400 hover:text-emerald-300 transition-colors py-1 px-2 rounded hover:bg-slate-800"
                    title="Take Reciprocal (1/x)"
                >
                    <RotateCcw size={12} />
                    <span>1/x</span>
                </button>
            )}
        </div>

        {/* Operation Controls */}
        <div className="flex flex-col items-center gap-3 z-10 bg-slate-900 p-2 rounded-xl border border-slate-700">
            <div className="flex gap-1 bg-slate-800 p-1 rounded-lg">
                <button
                    onClick={() => setSelectedOp('MULTIPLY')}
                    className={`p-2 rounded-md transition-all ${selectedOp === 'MULTIPLY' ? 'bg-indigo-600 text-white shadow-lg' : 'text-slate-400 hover:text-white hover:bg-slate-700'}`}
                    title="Multiply (A × B)"
                >
                    <X size={20} />
                </button>
                <button
                    onClick={() => setSelectedOp('POWER_AB')}
                    className={`p-2 rounded-md transition-all ${selectedOp === 'POWER_AB' ? 'bg-indigo-600 text-white shadow-lg' : 'text-slate-400 hover:text-white hover:bg-slate-700'}`}
                    title="Power (A ^ B)"
                >
                    <div className="flex items-start text-sm font-bold leading-none">
                        <span>A</span>
                        <span className="text-[10px] -mt-1">B</span>
                    </div>
                </button>
            </div>
        </div>

        {/* Slot B */}
        <div className="relative group">
            <Slot 
            label="Input B" 
            slotId="slotB"
            card={slotB} 
            onDrop={onDropOnSlot}
            onRemove={() => slotB && onReturnToHand(slotB)}
            onDragStart={onDragStart}
            highlight={!slotB}
            />
             {/* Reciprocal Action */}
             {slotB && (
                <button 
                    onClick={() => applyReciprocal('slotB', slotB)}
                    className="absolute -bottom-10 left-1/2 -translate-x-1/2 text-xs flex items-center gap-1 text-emerald-400 hover:text-emerald-300 transition-colors py-1 px-2 rounded hover:bg-slate-800"
                    title="Take Reciprocal (1/x)"
                >
                    <RotateCcw size={12} />
                    <span>1/x</span>
                </button>
            )}
        </div>

        {/* Result Preview / Action */}
        <div className="flex flex-col items-center">
            <ArrowRight className="md:hidden text-slate-600 my-2" />
            <div className={`
                w-36 h-24 rounded-xl border-2 transition-all duration-300 flex items-center justify-center
                ${preview 
                    ? 'border-emerald-500 bg-emerald-500/10 shadow-[0_0_20px_rgba(16,185,129,0.3)] cursor-pointer hover:scale-105 active:scale-95' 
                    : 'border-slate-800 bg-slate-900/50 opacity-50'
                }
            `}
            onClick={handleExecute}
            >
                {preview ? (
                    <div className="flex flex-col items-center text-emerald-400">
                        <span className="text-2xl font-bold font-mono">{preview.label}</span>
                        <span className="text-[10px] uppercase tracking-wider mt-1 font-semibold">Click to Create</span>
                    </div>
                ) : (
                    <div className="text-slate-600">
                        <Calculator size={32} />
                    </div>
                )}
            </div>
        </div>

      </div>
      
      <div className="text-center mt-6 text-slate-500 text-sm">
        Drag numbers to inputs • Select Operation • Click Result to Confirm
      </div>
    </div>
  );
};

export default Workbench;